services:
  database:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/seed.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  api:
    container_name: api
    build:
      context: api
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
    ports:
      - 8010:8010
    volumes:
      - ./api:/go/src/app
    depends_on:
      - database
  client:
    container_name: client
    build:
      context: client
    environment:
      - API_ENDPOINT=api:8010
      - NEXT_PUBLIC_API_ENDPOINT=api:8010
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
      - /app/client/.next
    ports:
      - 3000:3000
    depends_on:
      - database
      - api
